server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-route
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/products,/api/products/**
              filters:
                - RewritePath=/api/products(?<segment>/?.*), /products$\{segment}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
